### ISSUE TITLE
GSNv2 Support

### ISSUE THREAD

**Issue by naszam** [OpenZeppelin/openzeppelin-test-environment#139]
Hi, 

I would like to know if support for [GSNv2](https://docs.opengsn.org/learn/index.html) will be included in the OpenZeppelin Test Environment Roadmap.

Currently, the only way to test Paymaster and Meta Transactions can be done via Truffle Tests following [GSNv2 Integration Tutorial](https://docs.opengsn.org/tutorials/integration.html#automated_tests).

Would be great if GSNv2 will be supported in the future by OpenZeppelin Test Environment.

I've posted a related issue on [OpenZeppelin Forum](https://forum.openzeppelin.com/t/automated-tests-for-gsnv2-meta-txs-via-openzeppelin-test-environment/3898).

Thanks!

**Comment by abcoathup** [comment]
Hi @naszam!  Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by frangio** [comment]
Hi @naszam! We don't have any plans for shipping built-in support for GSNv2. I don't think you should have any issues with it, though! Note that Test Environment doesn't have built-in support for GSNv1 either, but it's possible to use it with the `setupProvider` configuration as shown in the [Getting Started](https://docs.openzeppelin.com/test-environment/0.1/getting-started) guide. I believe that this along with the GSNv2 documentation you linked should be enough to get started.
