### ISSUE TITLE
Provide sync accounts for Hardhat

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-test-environment#141]
Hardhat provides async accounts whilst OpenZeppelin Test Environment provides sync accounts

Reported by Anatol: https://t.me/BuidlerSupport/10401

**Comment by frangio** [comment]
This is not an issue in Test Env. Anatol was asking how to get Test Env's sync accounts behavior while using Hardhat.

Note that Hardhat Network and Test Env shouldn't be used together, because they spin up independent networks.
