### ISSUE TITLE
Why is it faster than `truffle test`?

### ISSUE THREAD

**Issue by lcswillems** [OpenZeppelin/openzeppelin-test-environment#164]
It is said everywhere it is faster than `truffle test`. But why? What is the thing you do differently and allows you to test faster?

**Comment by frangio** [comment]
Thank you for your question @lcswillems. The claim that it is faster is mostly based on empirical observation.

There are some things we know Truffle does and Test Environment doesn't. For example, Truffle loads all of the artifacts on startup from disk and these are often huge JSON files.

I don't know whether actually running the tests is also faster, as opposed to only startup time, and what this could be attributed to.
