### ISSUE TITLE
The ganache server doesn't exit gracefully when the test finishes too quickly

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-test-environment#19]
On test suites where there is no sync point (the provider is never `await`ed), and where the tests end too quickly, the ganache process throws an exception, I believe related to it being still initializing but having to suddenly exit.

We need to dig on what is actually going on to prevent this error from occurring.

**Comment by frangio** [comment]
We have to take a very good look at the error handling situation in the forked process, and make sure it's solid.

**Comment by sumitis14** [comment]
Also facing this issue.
Following this thread.

**Comment by nventuro** [comment]
@sumitis14 interesting, thanks for reporting! 

Could you share more information about your setup and the triggering of this bug?

**Comment by shark0der** [comment]
I might be facing the same bug. The problem arises when attempting to run the tests without compiled contracts. `@openzeppelin/contract-loader` attempts to read the contract and fails with `ENOENT`, mocha exits with status code 1, the shell prompt appears and only after the shell prompt this error pops up:

```
user@machine:/w/test-project$ npx mocha
Error: /w/test-project/build/contracts/MasterMock.json: ENOENT: no such file or directory, open '/w/test-project/build/contracts/MasterMock.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.readFileSync (/w/test-project/node_modules/jsonfile/index.js:61:22)
    at loadArtifact (/w/test-project/node_modules/@openzeppelin/contract-loader/lib/index.js:47:23)
    at TruffleLoader.BaseLoader.fromArtifact (/w/test-project/node_modules/@openzeppelin/contract-loader/lib/index.js:65:18)
    [snip]
user@machine:/w/test-project$
/w/test-project/node_modules/ganache-core/lib/subproviders/geth_api_double.js:39
        callback(self.initialization_error, self.state);
        ^
TypeError: Cannot read property 'port' of null
    at /w/test-project/node_modules/@openzeppelin/test-environment/src/ganache-server.ts:42:51
    at Immediate.<anonymous> (/w/test-project/node_modules/ganache-core/lib/subproviders/geth_api_double.js:39:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

It is extremely annoying because it pollutes the shell output.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-test-environment/commit/a55b8eb980ce3b31ed3093f74cd279e5f5afd2fc.
