### ISSUE TITLE
Integration of upcoming solidity-coverage release

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-test-environment#21]
A new version of `solidity-coverage` will be out soon, with some great improvements. It doesn't require a specialized version of the vm, only that it runs in-memory, which is something we're already doing.

Given that most of the hassle of setting up a coverage run involves tweaking the test environment (setting up gas prices, allowing large contracts, etc.), it'd be best if we could handle the whole configuration of `solidity-coverage`, so that the user simply says 'I want my tests to run in coverage mode'.

A couple things are however not clear:
 1. What is the API for setting up a coverage build? Given that `test-environment` is a library, the most convenient thing that I can think of is setting an environment variable that enables coverage, but this is a bit too restrictive. An alternative might be to have the environment variable instead contain the path of an alternative (coverage-oriented) configuration file, similar to the approach of tools such as `ts-node`. This goes in line with features such as alternative back-ends (see #20), which could each have their own config.
 1. `solidity-coverage` needs to know which command to use to compile the source files, so we'd still need the user to manually set up this configuration. An option would be to train our users to set this under the `compile` script (`npm run compile`) and simply use that. The fact that `compile` might also mean transpilation of TS into JS could cause issues.
 1. When using `jest`, `ava`, or any parallel test-runner, multiple process will be spawned. We'd need to somehow orchestrate the reports generated by each individual run to end up with a single coverage report.

**Comment by cgewecke** [comment]
Hi, just looking over your shoulder. Will be working on the coverage API over the next few days and this issue is really helpful for that. 

Some notes & questions ...

 > solidity-coverage needs to know which command to use to compile the source files

As planned, the API is slightly different than this - it takes an array of solidity sources to instrument and returns them to the consumer for compilation. (optimizer.enabled is not allowed though.)

> multiple process will be spawned 

Do you have a recommendation for an example of parallel tests?  Does it mean many ganache's on different ports or `ganache.provider` or ...? 

> orchestrate the reports generated by each individual run to end up with a single coverage report

One approach could be to combine the collected data *before* generating any reports. After tests finish, you would have several complete instrumentation maps, each containing a subset of the line hit data. In abbreviated form they look like this:
```javascript
instrumentation[unique_hash] = {
  hits: 0
}
```
You would select one as a base and iterate across the others, adding hits. Then pass the complete map to the API's reporter method which will handle the coverage report generation. Here I'm imagining there's some parent process that co-ordinates launching multiple clients and collating all the data. 

But there are also utilities like [istanbul-combine-updated][1] which might be a better solution. For that case, solidity-coverage needs to make sure it can be configured to write the report to an arbitrary location. 

[1]: https://www.npmjs.com/package/istanbul-combine-updated

**Comment by nventuro** [comment]
>Hi, just looking over your shoulder

Welcome :grin: 

>As planned, the API is slightly different than this - it takes an array of solidity sources to instrument and returns them to the consumer for compilation. The only restriction is that the instrumented contracts can't be compiled with optimization on.

Interesting! This does provide more flexibility to consumers. Does coverage expect the compilation artifacts to be stored in the file system, or are they forwarded as arguments?

>Do you have a recommendation for an example of parallel tests? Does it mean many ganache's on different ports or ganache.provider or ...?

I don't have a sample handy, nor do we have proper integration tests featuring this yet, but a good starting point would be our [jest tests](https://github.com/OpenZeppelin/openzeppelin-test-environment/tree/master/test-integration/jest). If you were to copy that project, install test-environment from npm, and add more test files, they'd all be run in parallel.

Regarding what parallel means, it depends. Ava does create new processes, while Jest uses a somewhat obscure feature of Node called [VM scripts](https://nodejs.org/api/vm.html#vm_vm_executing_javascript). In both cases however there will be multiple instances of `ganache-core`, running on different ports.

>Here I'm imagining there's some parent process that co-ordinates launching multiple clients and collating all the data.

There actually isn't, since we don't control the lifecycle of the process: the test runner does. However, we should be able to react to each independent runner finishing, and have each process append their results to a master file. We'd need to take care not to run into race conditions though.

>But there are also utilities like istanbul-combine-updated which might be a better solution. For that case, solidity-coverage needs to make sure it can be configured to write the report to an arbitrary location.

This is related to the issue above: since there's no parent process we control, even if we were to combine the reports I don't think we'd be able to upload them to e.g. coveralls, so we may end up providing users with a simple bash script for them to run after the test run. Said script could include the calls to `istanbul-combine-updated` (which seems to have a nice CLI!).

**Comment by cgewecke** [comment]
>  Does coverage expect the compilation artifacts to be stored in the file system, or are they forwarded as arguments?

The API doesn't directly manage how contracts or artifacts are stored - that's been delegated to plugin implementations which use the resources provided by their respective platforms. SC has a small suite of helpers for this purpose but they're incidental to the API.  

In practice the process has looked something like 
```javascript
// Psuedo-code
api = new CoverageAPI()

contracts = plugin.loadContracts()
instrumentedContracts = api.instrument(contracts)

plugin.saveTo(tempFolder, instrumentedContracts)
plugin.compileFrom(tempFolder)
```

In oz-test-environment, compilation happens separately and it seems like you would need to co-ordinate it's relationship with `api.instrument` somehow.

And you'd do something like: 

```javascript
// Pseudo-code

// When compiling....
instrumentedContracts = api.instrument(contracts)
data = api.getInstrumentationData();
save(data)

// Later, when launching client and testing
api = new CoverageAPI({
  istanbulFolder: 'random-path' // Name of place to deposit report
});

data = load(pathToData);
api.setInstrumentationData(data)

server = api.ganache(Ganache, autoLaunch=false)
server.listen(randomPort, etc...);

test();       // Can be in a different process
api.report(); // Must be in same process as server.listen

// Lastly..
combineCoverageReports() // Can be in a different process
``` 

Does that look like it would map correctly to ... ?

> There actually isn't, since we don't control the lifecycle of the process: the test runner does. However, we should be able to react to each independent runner finishing, and have each process append their results to a master file. We'd need to take care not to run into race conditions though.

The above is all WIP - if there's a way to support parallelization am definitely into making it work so any suggestions are welcome.

**Comment by nventuro** [comment]
Interesting! I'll need to look at this in more detail, but it does seem like it might work. Is the proposed API documented somewhere?

**Comment by cgewecke** [comment]
@nventuro Ok, sounds good. I will get the API docs finished this week and publish a new beta so you can experiment with it.

**Comment by cgewecke** [comment]
Published `0.7.0-beta.3` 
```
npm install --save-dev solidity-coverage@beta
```

**Resources**

[API documentation][1]
[Plugin implementations for reference][2]

Please just lmk about any improvements you can think of, including docs clarifications (or errors). Looking at the code here, the part that seems least clear to me is how to manage compilation. I think you will need to:

+ save an 'instrumentationData' map produced during compilation and reload it for each coverage client invocation
+ manage instrumented solidity sources / their compilation artifacts.. The existing plugins create temporary folders and tell the dev framework where everything should be fetched from/written to by setting relevant configuration paths. In Truffle those are named 'contracts_directory' etc... 

You might be able to do a lot of that in-flight, idk. You might also be able to [parallelize compilation][3].

[1]: https://github.com/sc-forks/solidity-coverage/blob/beta/docs/api.md#solidity-coverage-api
[2]: https://github.com/sc-forks/solidity-coverage/tree/beta/plugins
[3]: https://github.com/macor161/quantal

**Comment by jamesmorgan** [comment]
Hi everyone, just checking if we should be using `solidity-coverage@beta` yet - does this now work with OZ TE?

**Comment by chentschel** [comment]
> Hi everyone, just checking if we should be using `solidity-coverage@beta` yet - does this now work with OZ TE?

+1 :)

**Comment by abcoathup** [comment]
Update on solidity-coverage for Test Environment: 
https://forum.openzeppelin.com/t/openzeppelin-test-environment-roadmap-q2-2020/2557/21?u=abcoathup

**Comment by lcswillems** [comment]
@abcoathup I am quoting a part of the message you linked to:

> Shortly, we’ll release a new version of Test Environment library with solidity-coverage support and a guide how to setup for your project. OpenZeppelin Contracts library will use solidity-coverage feature to generate coverage reports.

Has the support for solidity-coverage been released? If yes, where is the guide?

**Comment by frangio** [comment]
@lcswillems Yes, there is support for solidity-coverage. In the end we didn't put together a guide because other projects have taken on greater priority for us. If you want to set it up I would recommend looking at [this integration test](https://github.com/OpenZeppelin/openzeppelin-test-environment/tree/master/test-integration/mocha), you should create a script like [`coverage.js`](https://github.com/OpenZeppelin/openzeppelin-test-environment/blob/master/test-integration/mocha/coverage.js) to run coverage.

You may have a smoother experience using the official Hardhat or Truffle coverage plugins.
