### ISSUE TITLE
RSKj integration

### ISSUE THREAD

**Issue by ilanolkies** [OpenZeppelin/openzeppelin-test-environment#37]
Hi team!

Currently in RSK network projects we are trying to build some “automagic” test environment and we found this library is quite suitable for our requirements. 

Instead of using ganache core, we would like to run tests against a local RSK node. 
Do you find suitable to integrate RSKj node as another option for running tests? 

Ref. on how to start a local RSK node: https://developers.rsk.co/quick-start/step1-install-rsk-local-node/

**Comment by abcoathup** [comment]
Hi @ilanolkies!  Thanks for the suggestion, it is really appreciated.

The project owner should review your suggestion during the next week. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by ilanolkies** [comment]
Thanks buddy!

**Comment by AuHau** [comment]
This would be very awesome! Let me know if I could help you with the work on it.

**Comment by frangio** [comment]
We would like to support alternative nodes eventually but it's not on our plans currently, and Geth would be a priority first. Apologies! Feel free to maintain a fork with support for RSKj.
